"""todo 2

Revision ID: 9e11abeb92b8
Revises: 2383007fdebe
Create Date: 2019-03-29 13:30:08.243639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e11abeb92b8'
down_revision = '2383007fdebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('date_due', sa.Date(), nullable=True))
    op.add_column('todo', sa.Column('date_made', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'date_made')
    op.drop_column('todo', 'date_due')
    # ### end Alembic commands ###
